[build]
base = "frontend"
# IMPORTANT: Switch from 'npm' to 'yarn' commands for the frontend build.
# 'yarn install --frozen-lockfile' ensures a clean and reproducible install from yarn.lock.
command = "npm install && npm run build"

publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
